apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.9

#helmCharts:
#- name: argocd
#  namespace: argocd
#  version: 4.10.6
#  repo: https://argoproj.github.io/argo-helm

resources:
  - applications.yaml

patchesStrategicMerge:
  - service.yaml
  - configmap.yaml

