apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/monitoring-ingress.yaml

helmCharts:
- name: kube-prometheus-stack
  namespace: monitoring
  version: 39.6.0
  repo: https://prometheus-community.github.io/helm-charts
